import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import Landing from "../components/Landing/Landing";
import { getHomepageCategories, getHomepageProduct } from "../queries/queries";
import ProductCard from "../widgets/ProductCard";
import Tab from "../widgets/Tab";

interface Post {
  id: string;
  title: string;
  slug: string;
  featured_image: {
    id: string;
  };
  body: string;
}

const Home = () => {
  const { data: products, isSuccess: isSuccessProduct } = useQuery<Product[]>({
    queryKey: ["products"],
    queryFn: async () => await getHomepageProduct(),
  });

  const { data: categories, isSuccess: isSuccessCategories } = useQuery<
    Category[]
  >({
    queryKey: ["categories"],
    queryFn: async () => await getHomepageCategories(),
  });

  // console.log(categories, "====================");

  if (isSuccessProduct && isSuccessCategories) {
    const tabTitle = categories.map((cat) => {
      const tabProducts = products.filter((product) => {
        return product.product_categories.some(
          (e) => e.Category_id.id === cat.id
        );
      });
      return {
        title: cat.category_name,
        children: (
          <div className="   grid  grid-cols-1 gap-11 sm:grid-cols-2 md:grid-cols-1 lg:grid-cols-3 ">
            {tabProducts.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        ),
      };
    });
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="relative h-[200vh] bg-[#E7ECEE]">
          <Landing />
        </main>
        <section className=" relative z-40 -mt-[100vh] min-h-screen bg-[#1B1B1B]">
          <div className="space-y-10 py-16">
            <h1 className="text-center text-4xl font-medium tracking-wide text-white md:text-5xl">
              محصولات جدید
            </h1>
            <div className="   mx-auto flex max-w-fit justify-center pt-10 pb-24 sm:px-4  ">
              <Tab tabs={tabTitle} />
            </div>
          </div>
        </section>
      </>
    );
  }
};

export default Home;
