import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import ProductCard from "../components/ProductCard";
import { getHomepageProduct } from "../queries/queries";

interface Post {
  id: string;
  title: string;
  slug: string;
  featured_image: {
    id: string;
  };
  body: string;
}

const Home = () => {
  const { data: posts, isSuccess } = useQuery<Post[]>({
    queryKey: ["posts"],
    queryFn: async () => await getHomepageProduct(),
  });
  if (isSuccess)
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          {posts.map((item) => (
            <div className="text-white" key={item.id}>
              <ProductCard
                image={item.featured_image}
                body={item.body}
                title={item.title}
              />
            </div>
          ))}
        </main>
      </>
    );
};

export default Home;
